algoritmo "referencia (procedimentos)"
var
   X, Y: Inteiro
Procedimento Soma ( var A, B: inteiro)
inicio
      A<- A + 1
      B <- B + 2
      Escreval (" valor de a a = " , A)
      EScreval ("valor de B= ", B)
      EScreval ("Soma A+B = ", A+B)
FimProcedimento
inicio
      X <-  4
      Y <-  8
      Soma (X,Y)
      escreval ("Valor de X=", X)
      Escreval ("valor de Y= ", Y)
fimalgoritmo